<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFrameworks>netcoreapp3.1;net8.0;net10.0</TargetFrameworks><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="Program.Track1.cs" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.Azure.Management.Compute" Version="24.1.0" /><PackageReference Include="Microsoft.Azure.Management.DataFactory" Version="2.3.1" /></ItemGroup></Project>
