<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'ManageIPAddress.Track1'">
    <BaseIntermediateOutputPath>obj/track1/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj/track1/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'MockArmServer'">
    <BaseIntermediateOutputPath>obj/mock-server/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj/mock-server/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
