<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFrameworks>netcoreapp3.1;net8.0;net10.0</TargetFrameworks><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="CpuTimeDiagnoser.cs" /><Compile Include="Program.GeneratedTrack1Benchmarks.cs" /></ItemGroup><ItemGroup><PackageReference Include="BenchmarkDotNet" Version="0.14.0" /><ProjectReference Include="CreateVirtualMachinesInParallel.Track1Generated.csproj" Aliases="Track1" /><ProjectReference Include="CreateVirtualMachinesInParallel.csproj" Aliases="Track2" /></ItemGroup></Project>
