<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="Azure.ResourceManager.Compute" Version="1.2.1" />
    <PackageReference Include="Azure.ResourceManager.Network" Version="1.6.0" />
    <PackageReference Include="Azure.ResourceManager.Storage" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CpuTimeDiagnoser.cs" />
    <Compile Remove="Program.Benchmarks.cs" />
    <Compile Remove="Program.GeneratedTrack1Benchmarks.cs" />
    <Compile Remove="Program.Track1Generated.cs" />
    <Compile Remove="Program.MockServer.cs" />
    <Compile Remove="Program.Track1.cs" />
  </ItemGroup>

</Project>
