<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.LatestBenchmarks.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <ProjectReference Include="CreateVirtualMachinesInParallel.Track1.csproj" Aliases="Track1" />
    <ProjectReference Include="CreateVirtualMachinesInParallel.Track2Latest.csproj" Aliases="Track2" />
  </ItemGroup>

</Project>
