<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net8.0;net10.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.Benchmarks.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <ProjectReference Include="ManageVirtualNetwork.Track1.csproj" Aliases="Track1" />
    <ProjectReference Include="ManageVirtualNetwork.csproj" Aliases="Track2" />
  </ItemGroup>

</Project>
