<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFrameworks>netcoreapp3.1;net8.0;net10.0</TargetFrameworks><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="Program.Track1Generated.cs" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.Azure.Management.Compute" Version="61.0.0" /><PackageReference Include="Microsoft.Azure.Management.Network" Version="26.0.0" /><PackageReference Include="Microsoft.Azure.Management.ResourceManager" Version="3.17.4-preview" /></ItemGroup></Project>
